export const games = [
  {
    id: "donkey-kong",
    name: "Donkey Kong",
    category: "80s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/donkeykong-poster.png')]",
    year: "1981",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: "Gerakkan Mario ke kiri dan ke kanan pada balok penopang, naik turun tangga dan hindari rintangan apa pun di jalan (baik dengan melompati, menghancurkannya  dengan palu, atau mengitarinya). Gim arcade ini terdiri dari 4 papan berbeda, yang Anda mainkan dalam urutan berbeda.",
  },
  {
    id: "pac-man",
    name: "Pac-Man",
    category: "80s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/pacman-poster.png')]",
    year: "1980",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: "Pemain harus mengontrol tokoh berwarna kuning bernama pac-man. Pac-man harus, memakan” titik-titik kecil berwarna kuning pada saat yang bersamaan akan terdapat hantu akan menangkap pac-man. Jika pemain dapat memakan seluruh titik kuning tanpa mati maka pemain akan naik ke level selanjutnya.",
  },
  {
    id: "mario-bros",
    name: "Mario Bros",
    category: "80s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/mariobros-poster.png')]",
    year: "1983",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#071444]",
    desc: "Gerakkan Mario ke kiri dan ke kanan pada balok penopang, naik turun tangga dan hindari rintangan apa pun di jalan (baik dengan melompati, menghancurkannya  dengan palu, atau mengitarinya). Gim arcade ini terdiri dari 4 papan berbeda, yang Anda mainkan dalam urutan berbeda.",
  },
  {
    id: "popeye",
    name: "Popeye",
    category: "80s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/popeye-poster.png')]",
    year: "1982",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: "Tujuan permainan ini adalah agar Popeye the Sailor mengumpulkan sejumlah item yang dijatuhkan oleh Olive Oyl, tergantung pada levelnya — 24 hati, 16 not musik, atau 24 huruf dalam kata.",
  },
  {
    id: "robotron",
    name: "Robotron",
    category: "80s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/robotron-poster.png')]",
    year: "1982",
    owner: "Vid Kidz",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: "Gim ini menggunakan skema kontrol dua joystick. joystick kiri mengontrol gerakan karakter di layar, sedangkan joystick kanan mengontrol arah tembakan senjata karakter. Kedua joystick memungkinkan arah input dalam salah satu dari delapan cara.",
  },
  {
    id: "maniac-mansion",
    name: "Maniac Mansion",
    category: "80s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/maniacmansion-poster.png')]",
    year: "1987",
    owner: "Lucasfilm Game",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Maniac Mansion adalah gim petualangan grafis di mana pemain menggunakan antarmuka titik-dan-klik untuk memandu karakter melalui dunia gim dua dimensi dan untuk memecahkan teka-teki. Lima belas perintah tindakan, seperti "Berjalan Ke" dan "Buka Kunci", dapat dipilih oleh pemain dari menu di bagian bawah layar.`,
  },
];
