export const games = [
  {
    id: "donkey-kong",
    name: "Donkey Kong",
    category: "80s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/donkeykong-poster.png')]",
    year: "1981",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: "Gerakkan Mario ke kiri dan ke kanan pada balok penopang, naik turun tangga dan hindari rintangan apa pun di jalan (baik dengan melompati, menghancurkannya  dengan palu, atau mengitarinya). Gim arcade ini terdiri dari 4 papan berbeda, yang Anda mainkan dalam urutan berbeda.",
  },
  {
    id: "pac-man",
    name: "Pac-Man",
    category: "80s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/pacman-poster.png')]",
    year: "1980",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: "Pemain harus mengontrol tokoh berwarna kuning bernama pac-man. Pac-man harus, memakan” titik-titik kecil berwarna kuning pada saat yang bersamaan akan terdapat hantu akan menangkap pac-man. Jika pemain dapat memakan seluruh titik kuning tanpa mati maka pemain akan naik ke level selanjutnya.",
  },
  {
    id: "mario-bros",
    name: "Mario Bros",
    category: "80s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/mariobros-poster.png')]",
    year: "1983",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#071444]",
    desc: "Gerakkan Mario ke kiri dan ke kanan pada balok penopang, naik turun tangga dan hindari rintangan apa pun di jalan (baik dengan melompati, menghancurkannya  dengan palu, atau mengitarinya). Gim arcade ini terdiri dari 4 papan berbeda, yang Anda mainkan dalam urutan berbeda.",
  },
  {
    id: "popeye",
    name: "Popeye",
    category: "80s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/popeye-poster.png')]",
    year: "1982",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: "Tujuan permainan ini adalah agar Popeye the Sailor mengumpulkan sejumlah item yang dijatuhkan oleh Olive Oyl, tergantung pada levelnya — 24 hati, 16 not musik, atau 24 huruf dalam kata.",
  },
  {
    id: "robotron",
    name: "Robotron",
    category: "80s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/robotron-poster.png')]",
    year: "1982",
    owner: "Vid Kidz",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: "Gim ini menggunakan skema kontrol dua joystick. joystick kiri mengontrol gerakan karakter di layar, sedangkan joystick kanan mengontrol arah tembakan senjata karakter. Kedua joystick memungkinkan arah input dalam salah satu dari delapan cara.",
  },
  {
    id: "maniac-mansion",
    name: "Maniac Mansion",
    category: "80s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/maniacmansion-poster.png')]",
    year: "1987",
    owner: "Lucasfilm Game",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Maniac Mansion adalah gim petualangan grafis di mana pemain menggunakan antarmuka titik-dan-klik untuk memandu karakter melalui dunia gim dua dimensi dan untuk memecahkan teka-teki. Lima belas perintah tindakan, seperti "Berjalan Ke" dan "Buka Kunci", dapat dipilih oleh pemain dari menu di bagian bawah layar.`,
  },
  {
    id: "sonic",
    name: "Sonic",
    category: "90s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/sonic-poster.png')]",
    year: "1991",
    owner: "SEGA",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Seri Sonic dicirikan oleh gameplay platform berbasis kecepatan.[ Mengontrol karakter pemain, pemain menavigasi serangkaian level dengan kecepatan tinggi sambil melompat antar platform, melawan musuh dan bos, dan menghindari rintangan. Serial ini berisi game 2D dan 3D`,
  },
  {
    id: "metal-slug",
    name: "Metal Slug",
    category: "90s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/metalslug-poster.png')]",
    year: "1996",
    owner: "SNK",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Aspek gimnya terdiri dari elemen lari dan tembak serta dalam rilis selanjutnya mekanisme tembak. Run and gun mengadu pemain melawan sejumlah besar musuh dengan pick-up senjata yang sangat kuat.`,
  },
  {
    id: "mortal-kombat",
    name: "Mortal Kombat",
    category: "90s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/mortalkombat-poster.png')]",
    year: "1991",
    owner: "Midway Games",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Pertandingan dibagi menjadi beberapa ronde, dan pemain pertama yang memenangkan dua ronde dengan menghabiskan bar kehidupan lawan sepenuhnya adalah pemenangnya. karakter yang kalah akan menjadi linglung dan pemenangnya diberi kesempatan untuk menggunakan gerakan finishing.`,
  },
  {
    id: "pokemon",
    name: "Pokemon",
    category: "90s",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/pokemon-poster.png')]",
    year: "1996",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Pemain dapat menggunakan Pokémon mereka untuk melawan Pokémon lain. Saat pemain bertemu dengan Pokémon liar atau ditantang oleh pelatih, layar beralih ke layar pertempuran berbasis giliran yang menampilkan dua Pokémon yang terlibat.`,
  },
  {
    id: "fallout",
    name: "Fallout",
    category: "90s",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/fallout-poster.png')]",
    year: "1998",
    owner: "Black Isle Studio",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Ketika seorang pemain menggunakan semua poin aksi mereka, mereka mengakhiri giliran mereka dan musuh memulai giliran mereka. Jika pemain bertahan tanpa cedera, poin aksinya dipulihkan.`,
  },
  {
    id: "super-metroid",
    name: "Super Metroid",
    category: "90s",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/supermetroid-poster.png')]",
    year: "1994",
    owner: "NINTENDO",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Samus dapat berlari, melompat, berjongkok, dan menembakkan senjata ke delapan arah, dia juga dapat melakukan tindakan lain, seperti lompat dinding—melompat dari satu dinding ke dinding lainnya secara berurutan untuk mencapai area yang lebih tinggi.`,
  },
  {
    id: "feeding-frenzy",
    name: "Feeding Frenzy",
    category: "00-09",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/feedingfrenzy-poster.png')]",
    year: "2006",
    owner: "Popcap Games",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Selama 40 level permainan, mereka mematikan antara 5 hewan laut. Tingkat terakhir adalah di mana mereka mencoba untuk melengserkan hiu besar, "Raja Hiu", menggunakan Orville si Orca. Pemain berperan sebagai spesies air yang berbeda, masing-masing mencoba naik ke rantai makanan. Saat ikan yang lebih kecil dimakan, ikan pemain sendiri bertambah besar dan mampu memakan ikan yang agak lebih besar.`,
  },
  {
    id: "guitar-hero",
    name: "Guitar Hero",
    category: "00-09",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/guitarhero-poster.png')]",
    year: "2005",
    owner: "RedOctane",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Saat bermain game, leher gitar yang diperpanjang ditampilkan secara vertikal di layar (fret horizontal), sering disebut "jalan raya nada", dan seiring berjalannya lagu, penanda berwarna atau "permata" yang menunjukkan nada berjalan di layar seiring waktu. musik; warna nada dan posisinya cocok dengan lima tombol fret pada pengontrol gitar.`,
  },
  {
    id: "hamster-ball",
    name: "Hamster Ball",
    category: "00-09",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/hamsterball-poster.png')]",
    year: "2004",
    owner: "Raptisoft",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Hamsterball dapat dikontrol dengan mouse, trackball, keyboard, atau joystick. Untuk bermain dengan mouse, dorong mouse Anda ke arah yang Anda inginkan untuk lari hamster. Semakin banyak Anda menggerakkan mouse, semakin cepat hamster Anda berlari ke arah itu. Anda dapat mengatur sensitivitas mouse di menu opsi.`,
  },
  {
    id: "plants-vs-zombie",
    name: "Plants vs Zombie",
    category: "00-09",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/plantszombies-poster.png')]",
    year: "2009",
    owner: "Popcap Games",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Pemain dapat memilih jenis tanaman dalam jumlah terbatas melalui paket benih di awal setiap level, dan harus membayar untuk menempatkannya menggunakan mata uang yang disebut "matahari".`,
  },
  {
    id: "gta-sa",
    name: "GTA San Andreas",
    category: "00-09",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/gta-poster.png')]",
    year: "2004",
    owner: "Rockstar",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Dengan berjalan kaki, karakter pemain mampu berjalan, berlari, berenang (permainan Grand Theft Auto pertama yang memungkinkan menyelam dan berenang tanpa tenggelam), memanjat terbatas, dan melompat, serta menggunakan senjata dan berbagai bentuk tangan ke tangan tempur.`,
  },
  {
    id: "counter-strike",
    name: "Counter Strike",
    category: "00-09",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/counterstrike-poster.png')]",
    year: "2000",
    owner: "Valve",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Dua tim lawan Teroris dan Kontra Teroris — bersaing dalam mode permainan untuk menyelesaikan tujuan, seperti mengamankan lokasi untuk menanam atau menjinakkan bom dan menyelamatkan atau menjaga sandera.`,
  },
  {
    id: "clash-of-clans",
    name: "Clash Of Clans",
    category: "10-16",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/coc-poster.png')]",
    year: "2012",
    owner: "Supercell",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Clash of Clans adalah game strategi multipemain daring yang diterbitkan oleh Supercell. Anda dapat membangun komunitas Anda sendiri, melatih pasukan, dan menyerang pemain lain.`,
  },
  {
    id: "cut-the-rope",
    name: "Cut The Rope",
    category: "10-16",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/cutrope-poster.png')]",
    year: "2010",
    owner: "Zeptolab",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Gim ini berkisar memberi makan makhluk bernama Om Nom dengan permen dengan memotong tali dengan cara tertentu, sambil menggunakan alat lain seperti gelembung dan bantalan udara untuk menghindari bahaya dan mengumpulkan bintang.`,
  },
  {
    id: "clash-royale",
    name: "Clash Royale",
    category: "10-16",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/clashroyale-poster.png')]",
    year: "2016",
    owner: "Supercell",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Clash Royale adalah permainan video menara terburu-buru yang menempatkan pemain dalam permainan yang menampilkan dua atau empat pemain (1v1 atau 2v2) di mana tujuannya adalah untuk menghancurkan sebagian besar menara lawan, dengan penghancuran "Menara Raja" menjadi kemenangan instan.`,
  },
  {
    id: "angry-gran-run",
    name: "Angry Gran Run",
    category: "10-16",
    gameCardTextColor: "text-[#FFFFFFDE]",
    bg: "bg-[url('/images/game-page/blue-bg.png')]",
    poster: "bg-[url('/images/game-page/angrygran-poster.png')]",
    year: "2013",
    owner: "AceViral",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-[#071444]",
    desc: `Lari, lompat, lari, dan geser ke sana kemari berton-ton rintangan yang berbeda yang harus dilewati pemain`,
  },
  {
    id: "8-pool",
    name: "8 Pool",
    category: "10-16",
    gameCardTextColor: "text-[#000000B8]",
    bg: "bg-[url('/images/game-page/green-bg.jpeg')]",
    poster: "bg-[url('/images/game-page/8pool-poster.png')]",
    year: "2010",
    owner: "Miniclip",
    titleBg: "bg-[url('/images/game-page/yellow-title.svg')]",
    descBg: "bg-[#203C28]",
    desc: `Permainan bola mudah dimenangkan. Anda hanya perlu memilih meja dan bersiap-siap. Bergabunglah dengan kami dan tantang permainan bola ini dalam mode PvP.`,
  },
  {
    id: "temple-run",
    name: "Temple Run",
    category: "10-16",
    gameCardTextColor: "text-[#FFF500B8]",
    bg: "bg-[url('/images/game-page/red-bg.png')]",
    poster: "bg-[url('/images/game-page/templerun-poster.png')]",
    year: "2011",
    owner: "Imagi Studio",
    titleBg: "bg-[url('/images/game-page/red-title.svg')]",
    descBg: "bg-orange-950",
    desc: `Anda telah mencuri idola terkutuk dari kuil, dan sekarang Anda harus lari untuk hidup Anda untuk menghindari Monyet Iblis Jahat menggigit tumit Anda. Gesek untuk berbalik, melompat dan meluncur untuk menghindari rintangan, mengumpulkan koin dan membeli power up, membuka karakter baru`,
  },
];
